### ISSUE TITLE
Locale file not loading

### ISSUE THREAD

**Issue by adilsoncarvalho** [svenfuchs/rails-i18n#519]
Hi,

I need to change some values from `rails-i18n` for `pt-BR` but I found an awkward situation.

My `pt-BR.yml` file is never loaded and to have those configurations loaded I must put its content inside another file.

My `config/application.rb`

```ruby
config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}').to_s]
config.i18n.available_locales = %i(en pt-BR)
config.i18n.default_locale = :'pt-BR'
```

My `config/locales/pt-BR.yml`

```yml
pt-BR:
  time:
    formats:
      default: ! '%d/%m/%Y %H:%M'
```

The result of `Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}').to_s]`

```ruby
2.2.0 :001 > puts Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}').to_s]
/vagrant/projeto/config/locales/devise.en.yml
/vagrant/projeto/config/locales/devise.pt-BR.yml
/vagrant/projeto/config/locales/devise_views.pt-BR.yml
/vagrant/projeto/config/locales/en.yml
/vagrant/projeto/config/locales/models/attributes-default.pt_BR.yml
/vagrant/projeto/config/locales/models/comments.pt-BR.yml
/vagrant/projeto/config/locales/models/service_order.pt-BR.yml
/vagrant/projeto/config/locales/models/task.pt-BR.yml
/vagrant/projeto/config/locales/pt-BR.yml
/vagrant/projeto/config/locales/pundit.en.yml
/vagrant/projeto/config/locales/pundit.pt-BR.yml
/vagrant/projeto/config/locales/simple_form.en.yml
/vagrant/projeto/config/locales/simple_form.pt-BR.yml
/vagrant/projeto/config/locales/views/comments.pt-BR.yml
/vagrant/projeto/config/locales/views/service_order.pt-BR.yml
/vagrant/projeto/config/locales/views/tasks.pt-BR.yml
 => nil
2.2.0 :002 > Rails.version
 => "4.2.0"
```

**Comment by Mingan** [comment]
I'm not using rails-i18n but only i18n (v 0.6.11 on Ruby 1.9.3) and I've recently encountered similar behaviour. Keys starting with activerecord.* from files config/locale/default/[locale].yml aren't loaded in any other but development environment.

The file is included and other keys from the same file are loaded and translated just fine (both plain and scoped). Can't pinpoint the time this occurred but the i18n gem version has been fixed since Dec' 14. I assume it is some strange interaction with another gem.

Does anyone has some idea?
