### ISSUE TITLE
"Zero" in french use "one" key and not "other"

### ISSUE THREAD

**Issue by pabois** [svenfuchs/rails-i18n#748]
My 'fr.yml' locale file:
remaining:
      one: "1 essai restant"
      other: "%{count} essais restants"

In console: 
I18n.locale = 'fr'
I18n.t('challenges.remaining', count: 2)
=> "2 essais restants"
I18n.t('challenges.remaining', count: 1)
=> "1 essai restant"
I18n.t('challenges.remaining', count: 0)
=> "1 essai restant"

(should be "0 essais restants")

**Comment by larouxn** [comment]
Hey pabois, according to the [docs](http://guides.rubyonrails.org/i18n.html#pluralization), you can add a `zero` key to your `fr.yml` file.
```yml
fr:
  challenges:
    remaining:
      zero: "0 essai restants"
      one: "1 essai restant"
      other: "%{count} essais restants"
```

**Comment by pabois** [comment]
Hello,

yes sure. I can - and I did - add a zero key.
But the default fallback for a zero entry should be "other", like it does for english, and not "one"

**Comment by michaelbaudino** [comment]
Hi @pabois,

There are a few extra details I'd like to add that might (hopefully!) be helpful:

* the `zero` tag is not used in French [source: the [CLDR Language Plural Rules](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#fr)]
* in fact, the `zero` tag is used only in languages where `0` has a specific grammar rule (in French it's the same rule as for `1`) [source: the [CLDR spec](http://cldr.unicode.org/index/cldr-spec/plural-rules#TOC-Choosing-Plural-Category-Names)]
* you should never hard-code a number into the translation value: in French, for example, the `one` rule is used for `1`, but also for `0`, `0.5`, `1.5`, … [sources: [CLDR Language Plural Rules](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#fr) and 5th bullet of [this _Académie Française_ FAQ entry](http://www.academie-francaise.fr/questions-de-langue#57_strong-em-nombres-criture-lecture-accord-em-strong)]
* in French, the result of your example should actually be singular: `0 essai restant`

So, to solve your example, you should simply use the following `fr.yml` to work with both `0`, `1` and `42`:
```
fr:
  challenges:
    remaining:
      one: "%{count} essai restant"
      other: "%{count} essais restants"
```

I hope this will help you rather than confuse you 🤗 

------
> ⚠️ 🇫🇷 Look out, French is messed up! The same example with another context (_e.g._ shoes instead of challenges) might expect to be pluralized even with `0` (because shoes are expected to go by pairs 🤷‍♂️) [source: [_Académie Française_ FAQ](http://www.academie-francaise.fr/questions-de-langue#77_strong-em-sans-chapeau-sans-chaussures-em-strong)]
> And as far as I know, there's no way to support this with `rails-i18n` 😢

**Comment by pabois** [comment]
Very clear, thanks
