### ISSUE TITLE
Add keys for success when creating/updating/destroying a model

### ISSUE THREAD

**Issue by gtarsia** [svenfuchs/rails-i18n#784]
When running the `scaffold_controller` generator, the following messages gets hardcoded:  
`%{model} was successfully created|updated|destroyed.`

[scaffold_controller code for `created`](https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/railties/lib/rails/generators/rails/scaffold_controller/templates/controller.rb.tt#L32).  

It'd be nice to have translations for that, but I'm not sure of two things:  
1) Wether this is a good feature?  
2) What would a good key be for this? I think `helpers.success.created|updated|destroyed` could be good ones.

**Comment by owlworks** [comment]
I think your idea is good. I often have rewritten the code yourself.
But it maybe should be discussed on rails(scaffold) repository, not here.

And its key is preferable that it includes 'scaffold' in my opinion .
(ex. scaffold.success.created

**Comment by jpgeek** [comment]
I too often wind up writing my own translation files to handle this message.  My impression is that this would fit well in rails-i18n.  Since there is already:
activerecord.errors.messages....
maybe just add something like:
activerecord.success.messages...
I think the actual message relates directly to ActiveRecord regardless of where it is displayed, so it fits better here than in the scaffold discussion.

**Comment by digitalfrost** [comment]
Closing - Please refer to #1008 to track this issue
