### ISSUE TITLE
English datetime.prompts.second should be singular

### ISSUE THREAD

**Issue by Silex** [svenfuchs/rails-i18n#844]
I think https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml#L103 should be `Second` instead of `Seconds`.

If you agree I'll make a PR.

**Comment by digitalfrost** [comment]
It seems logical that it should be _Second_.
However looking back it has always been _Seconds_ since 2012...
https://github.com/svenfuchs/rails-i18n/commit/46b1934e7cb2941341be11aa01b0cde86fc382f4#diff-e45dd30902957e5217c221963ab173b1
@kuroda - does this correspond to some historical quirk in rails or is it OK to change ?

**Comment by digitalfrost** [comment]
@Silex you are actually the author of the original file back in 2012...

**Comment by digitalfrost** [comment]
See #848

**Comment by Silex** [comment]
@digitalfrost: ah, funny I completely forgot about that.

Back then in #244 I simply copied the existing locale from `en-US`, so I just copied the error introduced in 668347a
