### ISSUE TITLE
Fallbacks not working when extending list of available locales

### ISSUE THREAD

**Issue by thisismydesign** [svenfuchs/rails-i18n#894]
I want to add a new locale without explicitly naming those already provided the gem:

`application.rb`
```ruby
config.i18n.available_locales = ['de-DE-x-custom-locale'] + I18n.available_locales
config.i18n.default_locale = 'de-DE-x-custom-locale'
config.i18n.fallbacks = true
```

```ruby
pp I18n.available_locales
# => [:"de-DE-x-custom-locale", de-DE, de, en, it, ....]
pp I18n.fallbacks[:"de-DE-x-custom-locale"]
# => [:"de-DE-x-custom-locale", :"de-DE-x-custom", :"de-DE-x", :"de-DE", :de]
pp I18n.fallbacks[:"de-DE"]
# => [:"de-DE", :de]
I18n.t("errors.messages.blank")
# => translation missing
```

I have no other I18n config in the app.

If I explicitly list `available_locales` the translation is found. I.e.
```ruby
config.i18n.available_locales = ['de-DE-x-custom-locale',  :"de-DE", :de, ....]
```

**Comment by rmlockerd** [comment]
I agree that this could be a bit confusing since the ``fallbacks`` mechanism deduces potential locales for you. But, ``available_locales`` is the ultimately the canonical list of locales that your application supports, and it would be likewise confusing to have a additional locales added dynamically without a clear idea of where they come from. 

In any case, we can get this behaviour you want by turning off strict enforcement of the available locales. Set ``config.i18n.enforce_available_locales = false`` to disable enforcement.

**Comment by thisismydesign** [comment]
@rmlockerd Thanks!
