### ISSUE TITLE
Campo em branco é um termo racista? / Is "campo em branco" a racist expression?

### ISSUE THREAD

**Issue by jrjoacir** [svenfuchs/rails-i18n#900]
Fiquei aqui pensando se a expressão de “**campo em branco**” não poderia trazer um viés de racismo estrutural e se de repente não poderíamos evitá-lo trocando o em **branco** por **vazio**. Sinceramente não encontrei um bibliografia falando de maneira profunda sobre o assunto, mas o fato é que emprestamos do inglês a palavra _blank_ (https://www.merriam-webster.com/dictionary/blank) que não tem relação com _white_ (https://www.merriam-webster.com/dictionary/white), então traduzimos _blank field_ como campo _em branco_.

I was think about if brazilian portuguese expression "**campo em branco**" is not a racist expression and if we should not avoid it exchange **branco** by **vazio**. Honestly, I did not find any article addressing this subject but, in fact, in brazilian portuguese we translated _blank_ (https://www.merriam-webster.com/dictionary/blank) as _white_ (https://www.merriam-webster.com/dictionary/white), however they have different meanings.

**Comment by pama** [comment]
I don't agree.

Expressions like "estar em branco", "ficar em branco", "lição em branco", "passar a noite em branco" are not related to race or skin color. If you look at a white paper, "espaço em branco" means exactly that ... nothing in that space. nothing between, that's why is "branco".

"branco" is some expressions means "vazio", like you state, but it's not quite the same if you try to replace it in the expressions I wrote as examples.

What we can discuss is what is more accurate, if "espaço em branco" ou "campo vazio". But no racism whatsoever.

**Comment by jrjoacir** [comment]
I understood your point of view although I don't agree. So we could discuss about "more accurate" expression.
What do you think we exchange _campo em branco_ by _campo vazio_? In Brazilian Portuguese _vazio_ is different of _branco_ and because of that I suggest to exchange this expression. I would like to listen other people opinions like @svenfuchs .

**Comment by jrjoacir** [comment]
No discussion, no thoughts, no answer.

**Comment by jrjoacir** [comment]
Why?
