### ISSUE TITLE
Extract a South Slavic pluralizer

### ISSUE THREAD

**Issue by toncid** [svenfuchs/rails-i18n#986]
Hello,

This is a follow-up of #972. The Serbian pluralizer can/should be used for the three languages in the region (`hr`, `sr`, `bs`), because they do not need the `many` form as other East Slavic languages.

Just `one`, `few` and `other` are sufficient.

Source: https://www.unicode.org/cldr/cldr-aux/charts/29/supplemental/language_plural_rules.html#hr-comp

"South Slavic" might be too wide, as the above does not apply to Slovenian, Macedonian and Bulgarian.

**Comment by gregorbg** [comment]
Hey! We're running into an interesting issue here, because we use user-contributed locale files on our website. The translators usually don't have any technical/IT expertise, so we give them a web UI to translate that generates the YML files automatically.

This change made it so that our `hr` file looses a lot of `*.many` keys that were previously there. Unfortunately, we also have a CI check for I18N keys that uses the https://github.com/glebm/i18n-tasks gem to check locales on submission. It runs into a conflict because:

- Your gem removes the `many` keys
- The `i18n-tasks` gem expects the keys to be there
    - This is because it relies on the `iso` package, which **includes** `many` in its specification for `hr`: https://github.com/Locale/iso/blob/8e7c979bf5d9ab231356322ee5d6bec88950255e/data/iso-639-1.yml#L90-L95
    
Now the big question is: How to fix this? Is your gem at fault for removing the `many` pluralizer here? Or is the `iso` package out of date and should be updated? Any idea is welcome :)

Thanks!

**Comment by toncid** [comment]
Hello, as a native Croatian speaker, I can tell you that there is no use case for `many`. There is no need for it, as `one`, `few` and `other` cover all possible cases.

In this case, the `iso` gem is out of date, so I would recommend sending a PR their way. In the meantime, make sure your entries for `many` and `other` are the same to prevent data loss and be future-proof.

Hope this helps!

**Comment by gregorbg** [comment]
Cool, thanks for the feedback! This helps a lot and I will prepare a PR towards the `iso` gem.

Do you have any further information on how to interpret the Unicode link you posted above in relation to the concrete `pluralization` key changes? Since we're talking about updating an ISO gem, I would need the ISO itself as a source to justify the PR. And even though it's very technically sophisticated, from my understanding Unicode != ISO.

**Comment by toncid** [comment]
You're welcome. 👍 I would just use the Unicode page as a reference, because there are no ISO pluralization rules to my knowledge.
